# Generated by Django 5.2.8 on 2025-12-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_width_width_name_alter_fabric_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='first_page',
            field=models.BooleanField(default=False, null=True, verbose_name='نمایش در صفحه اول'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='first_page',
            field=models.BooleanField(default=False, null=True, verbose_name='نمایش در صفحه اول'),
        ),
        migrations.AddField(
            model_name='usage',
            name='first_page',
            field=models.BooleanField(default=False, null=True, verbose_name='نمایش در صفحه اول'),
        ),
    ]
