# Generated by Django 5.2.8 on 2026-02-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_fabric_first_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='width',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabrics', to='shop.width', verbose_name='عرض پارچه'),
        ),
        migrations.CreateModel(
            name='FabricImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fabric_images', verbose_name='تصویر')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.fabric', verbose_name='تصویر پارچه')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
    ]
