# Generated by Django 5.2.8 on 2026-02-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_fabricimages_image_fabric_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FabricImages',
        ),
    ]
