# Generated by Django 5.2.8 on 2026-02-10 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_fabric_image_fabricimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricimages',
            old_name='image',
            new_name='original_image',
        ),
        migrations.AlterField(
            model_name='fabric',
            name='width',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabric', to='shop.width', verbose_name='عرض پارچه'),
        ),
        migrations.AlterField(
            model_name='fabricimages',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.fabric', verbose_name='پارچه'),
        ),
    ]
