# Generated by Django 5.2.8 on 2026-02-13 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_fabricimages_fabric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricimages',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.fabric', verbose_name='پارچه'),
        ),
    ]
