# Generated by Django 5.2.8 on 2025-11-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='رنگ پارچه')),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'رنگ پارچه',
                'verbose_name_plural': 'رنگ های پارچه',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='جنس پارچه')),
            ],
            options={
                'verbose_name': 'جنس پارچه',
                'verbose_name_plural': 'جنس های پارچه',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='طرح پارچه')),
            ],
            options={
                'verbose_name': 'طرح پارچه',
                'verbose_name_plural': 'طرح های پارچه',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='کاربرد پارچه')),
            ],
            options={
                'verbose_name': 'کاربرد پارچه',
                'verbose_name_plural': 'کاربردهای پارچه',
            },
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(verbose_name='عرض پارچه')),
            ],
            options={
                'verbose_name': 'عرض پارچه',
                'verbose_name_plural': 'عرض های پارچه',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان')),
                ('thickness', models.CharField(choices=[('thin', 'نازک'), ('normal', 'معمولی'), ('thick', 'ضخیم')], max_length=10, verbose_name='ضخامت پارچه')),
                ('inventory', models.FloatField(default=0, verbose_name='مقدار موجودی پارچه')),
                ('price', models.IntegerField()),
                ('color', models.ManyToManyField(to='shop.color', verbose_name='رنگ پارچه')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.material', verbose_name='جنس پارچه')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.pattern', verbose_name='طرح پارچه')),
                ('usage', models.ManyToManyField(to='shop.usage', verbose_name='کاربرد پارچه')),
                ('width', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.width', verbose_name='عرض پارچه')),
            ],
            options={
                'verbose_name': 'پارچه',
                'verbose_name_plural': 'پارچه ها',
            },
        ),
    ]
