# Generated by Django 5.2.8 on 2025-12-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='width',
            old_name='width',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='fabric',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
