# Generated by Django 5.2.8 on 2025-12-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_material_first_page_pattern_first_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='first_page',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اول'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='first_page',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اول'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='first_page',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اول'),
        ),
    ]
