# Generated by Django 5.2.8 on 2025-12-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_material_first_page_alter_pattern_first_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='first_page',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اول'),
        ),
    ]
