# Generated by Django 5.2.8 on 2026-02-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_fabric_width_fabricimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricimages',
            name='image',
        ),
        migrations.AddField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images', verbose_name='تصویر'),
        ),
    ]
