# Generated by Django 5.2.8 on 2026-02-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_image_fabricimages_original_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='usage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر'),
        ),
    ]
