# Generated by Django 5.2.8 on 2026-02-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_pattern_original_image_usage_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='pattern_images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='usage_images', verbose_name='تصویر'),
        ),
    ]
